---
:exception_notification: false
:exception_notification_sender: Sender Name <nobody@localhost>
:exception_notification_receipients: nobody@localhost
:invoice_style: default
:reports:
  :style: default
app_name: "Salor"
technician_code: U9479880090210
stylesheets: 'darker'
version: "1.6.10"
standalone: true
roleless: false
locale: 'en-US'
base_locale: 'en-US'
license: "M"
dt_tags: true
dt_tags_values: Lotto,Toto
convert_from_gross: true
height_metrics: MM,CM,DM,M
length_metrics: MM,CM,DM,M
width_metrics: MM,CM,DM,M
weight_metrics: STK,BD,BT,CM,GR,KG,LT,ML,MT,PA,PK,PT,RL,ST,TB,WG
sales_metrics: STK,BD,BT,CM,GR,KG,LT,ML,MT,PA,PK,PT,RL,ST,TB,WG
reorder_csvs: true
reorder_types: default_export:Default,tobacco_land:TobaccoLand
item_limit: 0
order_limit: 0
general:
  per_page: 5
items:
  order: "id DESC"
  per_page: 5
  search:
    per_page: 35
categories:
  per_page: 5
locations:
  per_page: 5
orders:
  per_page: 10
  order: "id DESC"
vendors:
  per_page: 5
customers:
  per_page: 10
  search:
    per_page: 35
employees:
  jailed: true
  per_page: 5
shippers:
  per_page: 5
discounts:
  per_page: 10
costs:
  vendors: 0.50
  items: 0.0095
  dummy_items: 0.0049
  tax_profiles: 0.059
  orders: 0.0012
  order_items: 0.00072
  registers: 0.25
  employees: 0.159
  shipment_items: 0.00061
mail:
  enable_ssl: false
  address: ''
  port: 110
  user_name: None
  password: None
  
  
  
